# Generated by Django 4.0.3 on 2022-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='U_Id',
        ),
        migrations.AddField(
            model_name='reports',
            name='Name',
            field=models.CharField(default='Mark', max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reports',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
