# Generated by Django 4.0.3 on 2022-06-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_reports_u_id_reports_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='AssembleDestination_Current',
            new_name='Reasons',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='AssembleDestination_Request',
            new_name='Ride_Current',
        ),
        migrations.AddField(
            model_name='requests',
            name='Ride_Request',
            field=models.CharField(default='Helwan', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
