# Generated by Django 4.0.3 on 2022-06-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_assembledestination_current_requests_reasons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='Licence',
            new_name='LicenceNumber',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
