# Generated by Django 4.0.3 on 2022-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_licence_vehicles_licencenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='userId',
        ),
        migrations.AlterField(
            model_name='rides',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
