# Generated by Django 4.0.4 on 2022-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_rides_userid_alter_rides_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=250, null=True, unique=True),
        ),
    ]
