# Generated by Django 4.0.4 on 2022-06-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='AssemblePoint',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='DriverLicence',
        ),
    ]
