# Generated by Django 4.0.3 on 2022-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblePoints',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('R_Name', models.CharField(max_length=100)),
                ('R_Code', models.CharField(max_length=100)),
                ('R_Location', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('AssemblePoints', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('U_Id', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('R_Names', models.CharField(max_length=100)),
                ('R_Codes', models.CharField(max_length=100)),
                ('AssembleDestination_Current', models.CharField(max_length=100)),
                ('AssembleDestination_Request', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('RideName', models.CharField(max_length=100)),
                ('RideCode', models.CharField(max_length=100)),
                ('AssembleDestination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('RouteName', models.CharField(max_length=100)),
                ('RouteCode', models.CharField(max_length=100)),
                ('StartPoint', models.CharField(max_length=100)),
                ('EndPoint', models.CharField(max_length=100)),
                ('DriverLicence', models.IntegerField()),
                ('VehicleLicence', models.IntegerField()),
                ('AssemblePoint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('DriverName', models.CharField(max_length=200, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('LicenseNumber', models.IntegerField()),
                ('LicenseEnd', models.IntegerField()),
                ('Ride', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleModel', models.CharField(max_length=100)),
                ('VehicleCapacity', models.IntegerField()),
                ('Licence', models.CharField(max_length=100)),
                ('EndLicence', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
